logo_title: Wei OUYANG

style: black

favicon: /favicon.ico

menu:
  Projects: /project
  Links: /links
  About: /about
  Github: https://github.com/oeway

valine:
  appId: 
  appKey: 

highlight:
  enable: false